---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install apps
    apt:
      name:
        - neofetch
        - cmatrix
      state: latest
    when: ansible_distribution == "Debian"


  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: install apps
    dnf:
      name:
        - neofetch 
        - cmatrix
      state: latest
    when: ansible_distribution == "Rocky"
