---

- hosts: all
  become: true
  tasks:


  - name: install apps
    apt:
      name:
        - neofetch
        - cmatrix
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"


  - name: install apps
    dnf:
      name:
        - neofetch 
      state: latest
      update_cache: yes
    when: ansible_distribution == "Rocky"
