---

- hosts: all
  become: true
  tasks:
  pre_tasks:

  - name: update repo cache (Rocky)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Rocky"


  - name: update repo cache (Debian)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"



- hosts: all
  become: true
  roles:
    - base
 



- hosts: workstations
  become: true
  roles:
    - workstations

